HD-343
hashdata-org/docs pull request #3
Opened 2024-11-22 23:43 UTC by AdmilsonGoncalves

2024-11-25 19:24 UTC, ModestinoAndre requested changes

2024-11-25 19:24 UTC, ModestinoAndre commented on docs/start-here/migration/for-users.mdx
> +as cidades da cada Unidade da Federação.
`de` cada Unidade da...

2024-11-25 19:24 UTC, ModestinoAndre commented on docs/start-here/migration/for-users.mdx
> +Quando a lógica de navegação está habilitada, as questões são mostradas uma por vez, ou seja, uma por página, pois as
As questões não são mostradas uma por vez, na verdade, o sistema exibe as questões até encontrar uma LN, neste ponto ele para e aguarda o usuário clicar em avançar.

2024-11-25 19:24 UTC, ModestinoAndre commented on docs/start-here/migration/whats-news.mdx
> +sidebar_label: O que há de ovo?
typo: ovo (novo)

2024-11-25 19:24 UTC, ModestinoAndre commented on docs/start-here/migration/for-users.mdx
> +Utilizando-se do recurso de lógica de navegação, seria necessária a seguinte configuração:
lógica de exibição

2024-11-26 15:03 UTC, AdmilsonGoncalves commented on docs/forms/actions.mdx
> +cujas respostas serão usadas para identificar as coletas pendentes.
Veja se é isso que você pediu. Embora o formulário fica como pendnete no mobile, no desktop, na opção do menu principal 'Respostas Pendentes', não aparece nada. Imaginei que se tratava da mesma coisa. Explique, por favor.

2024-12-01 14:45 UTC, AdmilsonGoncalves commented on docs/forms/how-to-publish-the-form.mdx
> +- Durante a publicação, é obrigatório informar uma **data de validade**, que define até quando o formulário poderá ser respondido;
Não sei de onde tirei que é obrigatória.

2024-12-02 18:32 UTC, ModestinoAndre commented on docs/forms/elements/elements.mdx
> +            Por exemplo, em campo de unidades de medidas ou distâncias, os sufixos poderiam ser: "kg" e "km ".
Não dá pra colocar no código porque há casos onde os clientes desejam usar o prefixo ou sufixo sem o espaço, por exemplo, nos EUA é comum usar valores assim: 50$ (sem espaço).

2024-12-02 18:50 UTC, ModestinoAndre approved these changes
Ver os comentários que ficaram em aberto.
Já vou efetuar o merge e deploy.

2024-12-02 18:51 UTC, merged