HD-352
hashdata-org/docs pull request #4
Opened 2024-12-08 22:42 UTC by AdmilsonGoncalves

2024-12-09 20:16 UTC, ModestinoAndre requested changes

2024-12-09 20:16 UTC, ModestinoAndre requested changes
...

2024-12-11 15:42 UTC, AdmilsonGoncalves commented on docs/forms/setting-up-forms-access.mdx
> +        s2n2["Conceda, aos \n grupos, acesso \n às pastas"]
Como é facultativo, tirei.

2024-12-16 22:33 UTC, ModestinoAndre approved these changes

2025-01-06 17:10 UTC, merged